### ISSUE TITLE
can't install gui

### ISSUE THREAD

**Issue by harriott** [abarker/pdfCropMargins#44]
(`Python 3.10.8`, `pip 22.3.1`) `[gui]` option isn't accepted by `pip`:
```bash
$ pip3 install pdfCropMargins[gui] --user --upgrade
ERROR: You must give at least one requirement to install (see "pip help install")
```

**Comment by abarker** [comment]
It's working fine for me with Python 3.8.10 and the same pip version on Ubuntu.  What OS are you running it on?

**Comment by abarker** [comment]
As a workaround, if you can install using the command without the `[gui]` part then the GUI should still work if you also run:
```
pip3 install PySimpleGUI PyMuPDF --user --upgrade
```

**Comment by harriott** [comment]
Right now I've `linux 6.0.10.arch2-1`. Just tested the `pip3 install` again - still fails.

With `PySimpleGUI` installed from AUR package [python-pysimplegui](https://aur.archlinux.org/packages/python-pysimplegui) and `PyMuPDF` installed from Arch community package [python-pymupdf](https://archlinux.org/packages/community/x86_64/python-pymupdf/), `pipx install pdfCropMargins` then
```bash
$ pdf-crop-margins -gui pdf.pdf
Error in pdfCropMargins: The GUI feature requires PyMuPDF
```
So something not connecting there. My fix is to use AUR package [pdfcropmargins](https://aur.archlinux.org/packages/pdfcropmargins), which allows access to the GUI.

**Comment by abarker** [comment]
I just uploaded a new version of pdfCropMargins with some updates.  The `[gui]` install option is no longer supported since the default install now includes the GUI dependencies.  Just using `pip3 install pdfCropMargins --user --upgrade` should work unless there is some other problem.

I didn't know that Arch Linux had the package in its distribution.

**Comment by harriott** [comment]
Yes, your v1.1.1 works. Having removed the AUR version,
```bash
pipx install pdfCropMargins
pdfcropmargins -gui pdf.pdf
```
\- thanks!

**Comment by abarker** [comment]
FYI, since you use the GUI, I just pushed out version 1.1.4 which has some improvements to the GUI interface.

**Comment by harriott** [comment]
Something's broken in `v1.1.4`. Just tried on 5 different pdf's, including that which worked fine in `v1.1.1`, it's like this now:
```bash
$ pdf-crop-margins s6201.pdf

Caught an unexpected exception in the pdfCropMargins program.
Unexpected error:  <class 'UnboundLocalError'>
Error message   :  local variable 'delta_page_nums' referenced before assignment

  File "/home/jo/.local/pipx/venvs/pdfcropmargins/lib/python3.10/site-packages/pdfCropMargins/pdfCropMargins.py", line 59, in main
    crop()
  File "/home/jo/.local/pipx/venvs/pdfcropmargins/lib/python3.10/site-packages/pdfCropMargins/pdfCropMargins.py", line 172, in crop
    output_doc_pathname = main_crop(argv_list)
  File "/home/jo/.local/pipx/venvs/pdfcropmargins/lib/python3.10/site-packages/pdfCropMargins/main_pdfCropMargins.py", line 1452, in main_crop
    bounding_box_list, delta_page_nums = process_pdf_file(input_doc_pathname,
  File "/home/jo/.local/pipx/venvs/pdfcropmargins/lib/python3.10/site-packages/pdfCropMargins/main_pdfCropMargins.py", line 1274, in process_pdf_file
    crop_list, delta_page_nums = calculate_crop_list(full_page_box_list, bounding_box_list,
  File "/home/jo/.local/pipx/venvs/pdfcropmargins/lib/python3.10/site-packages/pdfCropMargins/main_pdfCropMargins.py", line 560, in calculate_crop_list
    return final_crop_list, delta_page_nums
```

**Comment by abarker** [comment]
Thanks, my testing was leaving out some cases.  I pushed out a bug fix 1.1.5, which fixes that issue.

**Comment by pavel-razgovorov** [comment]
Hello. Installing through `pipx` in Mac OS Ventura (Intel) is still not working:

```console
$ pdf-crop-margins --version
pdfCropMargins 2.0.3
$ sw_vers
ProductName:		macOS
ProductVersion:		13.4.1
ProductVersionExtra:	(c)
BuildVersion:		22F770820d
$ pdf-crop-margins -gui Students\ book.pdf

Error in pdfCropMargins: The GUI feature requires PySimpleGUI.

Exiting pdfcropmargins...
```

Shall I open a new issue?

**Comment by abarker** [comment]
Yes, that should be a different issue.  I don't use Mac or pipx (just the regular pip).  How are you installing pdfCropMargins?  It seems that the PySimpleGUI dependency is not getting installed in the same environment.  What happens if you also install PySimpleGUI the same way, inside that same environment?

**Comment by mmohammadi9812** [comment]
> Hello. Installing through `pipx` in Mac OS Ventura (Intel) is still not working:
> 
> ```
> $ pdf-crop-margins --version
> pdfCropMargins 2.0.3
> $ sw_vers
> ProductName:		macOS
> ProductVersion:		13.4.1
> ProductVersionExtra:	(c)
> BuildVersion:		22F770820d
> $ pdf-crop-margins -gui Students\ book.pdf
> 
> Error in pdfCropMargins: The GUI feature requires PySimpleGUI.
> 
> Exiting pdfcropmargins...
> ```
> 
> Shall I open a new issue?

I had the same problem with GUI, installing `python-tk` with `homebrew` and reinstalling the package fixed it for me
